# CONFIGURATION POSTGRESQL
spring.datasource.url=jdbc:postgresql://postgresql-baptistefaugeres.alwaysdata.net:5432/baptistefaugeres_isis_archivage
spring.datasource.username=baptistefaugeres
spring.datasource.password=Baptiste05
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURATION HIBERNATE
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=${PORT:8080}