# CONFIGURATION POSTGRESQL
spring.datasource.url=jdbc:postgresql://postgresql-baptistefaugeres.alwaysdata.net:5432/baptistefaugeres_isis_archivage
spring.datasource.username=baptistefaugeres
spring.datasource.password=Baptiste05
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURATION HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=${PORT:8080}

# Limite la taille maximale d'un seul fichier (ex: 5 Mégaoctets)
spring.servlet.multipart.max-file-size=4MB

# Limite la taille totale de la requête (utile si on envoie plusieurs fichiers d'un coup)
spring.servlet.multipart.max-request-size=5MB